### ISSUE TITLE
Now and Happening

### ISSUE THREAD

**Issue by luke-xlab** [luke-xlab/website-replication#1]
I cannot seem to figure out the height and width of all of the boxes on the page. I need to put a border on them that is 1px wide. When I do that, it screws up the whole page and the boxes lose their positioning. I move the height and width in by 1px and it also screws up the page. The positioning is relative on all of them and they are floating left and right. 
![screen shot 2015-06-14 at 10 58 50 am](https://cloud.githubusercontent.com/assets/12883759/8149303/62925c68-1284-11e5-8d2d-74829f524465.png)
![screen shot 2015-06-14 at 10 59 49 am](https://cloud.githubusercontent.com/assets/12883759/8149306/6828a588-1284-11e5-9952-47dce1e117c4.png)

**Comment by luke-xlab** [comment]
If you need to look at original website, here you go: http://thinkblink.nl/

**Comment by hunterbrowning** [comment]
@luke-xlab Does the current state of the code have this bug in it or am I going to have to add a border to generate it?

**Comment by luke-xlab** [comment]
The current state does not have the bug in it. The boxes are lined up perfectly without the border

**Comment by hunterbrowning** [comment]
@luke-xlab Lets do this, create a new branch named "box-layout-fix", make the changes to that branch so the bug exist. Push that branch up and create a pull request. I will give feedback on it and then when we get it fixed, we will merge it back in. You always want the code associated with an issue to be logged in to source control (just never on the master branch). Make sense?

**Comment by luke-xlab** [comment]
That makes sense. I will do that now.
