### ISSUE TITLE
CSS Class Naming Conventions

### ISSUE THREAD

**Issue by hunterbrowning** [luke-xlab/website-replication#2]
Getting used to the -/__/-- conventions can take a second. Here are some recommendations of how I would change a few things and then you can see where else they are applicable in your code and adjust accordingly. 

`<div class="fixed__menu">` => `<div class="fixed-menu">`
then 
`<div class="menu__top">` => `<div class="fixed-menu--top">`
then
`<div class="menu__middle">` => `<div class="fixed-menu--middle">`
etc.

This is a tricky use case because it could go a little bit either way, but in my opinion the above is more correct. 

Single dashes (-) is really just replacing spaces and combining a name.
Double underscores (__) are to show nested possession. In your cause, you could argue that that is the case with the top, middle and bottom element. But...
Double dashes (--) show permutations/positions. Typically, if I see words like top, middle, bottom, left, right, I think of them as a position permutation of an original element. Do that is why in this specific case I would say double dashes are more accurate. 

Make sense? You are welcome to disagree obviously. Stylistic things can be tricky and everyone sees things slightly differently but I think the above logic is pretty sound.

**Comment by luke-xlab** [comment]
That makes sense. I agree with the position permutation. I will change those to double dashes
