### ISSUE TITLE
CSS Class Name Specificity

### ISSUE THREAD

**Issue by hunterbrowning** [luke-xlab/website-replication#3]
In general, we want class names to be as highly specific as possible. 

Things like using "homepage" as a root in `<div class="homepage__large-text">` seems misleading because really this entire page is the home page and that is just the main section. 

Using the word section in these sections would give someone who is reading the code and has never see the site a much better assumption of what you are actually creating. 

Look at this in all your code.

**Comment by luke-xlab** [comment]
So i should change it to main-large-text?

**Comment by hunterbrowning** [comment]
main is not very descriptive. Neither is "large-text" how about something like hero-text  (hero is often used to describe the main piece of content per type in a section) or even probably more appropriately, `.background-video__hero-text`
